ROLE_REPORTER = 'Reporter'
ROLE_AGENT = 'Agent'
ROLE_ADMIN = 'Admin'

ROLES = [ROLE_REPORTER, ROLE_AGENT, ROLE_ADMIN]

TYPE_BUG = 'Bug'
TYPE_INCIDENT = 'Incident'

TYPES = [TYPE_BUG, TYPE_INCIDENT]

PRIORITY_LOW = 'Low'
PRIORITY_MEDIUM = 'Medium'
PRIORITY_HIGH = 'High'
PRIORITY_CRITICAL = 'Critical'

PRIORITIES = [PRIORITY_LOW, PRIORITY_MEDIUM, PRIORITY_HIGH, PRIORITY_CRITICAL]

STATUS_OPEN = 'Open'
STATUS_IN_PROGRESS = 'In Progress'
STATUS_RESOLVED = 'Resolved'
STATUS_CLOSED = 'Closed'

STATUSES = [STATUS_OPEN, STATUS_IN_PROGRESS, STATUS_RESOLVED, STATUS_CLOSED]
