"""Remove old role string column

Revision ID: 0381926ca179
Revises: b0aebf30b6df
Create Date: 2026-09-24 15:19:48.372295

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0381926ca179'
down_revision = 'b0aebf30b6df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', mysql.VARCHAR(length=20), nullable=True))
        batch_op.alter_column('role_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
